/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index'
import { Route as PublicSignupRouteRouteImport } from './routes/public/signup/route'
import { Route as PublicSigninRouteRouteImport } from './routes/public/signin/route'
import { Route as PublicProcessRouteRouteImport } from './routes/public/process/route'
import { Route as PublicLandingRouteRouteImport } from './routes/public/landing/route'
import { Route as DashboardProjectsIndexRouteImport } from './routes/dashboard.projects.index'
import { Route as DashboardProjectsProjectIdRouteImport } from './routes/dashboard.projects.$projectId'

const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const PublicSignupRouteRoute = PublicSignupRouteRouteImport.update({
  id: '/public/signup',
  path: '/public/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicSigninRouteRoute = PublicSigninRouteRouteImport.update({
  id: '/public/signin',
  path: '/public/signin',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicProcessRouteRoute = PublicProcessRouteRouteImport.update({
  id: '/public/process',
  path: '/public/process',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicLandingRouteRoute = PublicLandingRouteRouteImport.update({
  id: '/public/landing',
  path: '/public/landing',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardProjectsIndexRoute = DashboardProjectsIndexRouteImport.update({
  id: '/projects/',
  path: '/projects/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardProjectsProjectIdRoute =
  DashboardProjectsProjectIdRouteImport.update({
    id: '/projects/$projectId',
    path: '/projects/$projectId',
    getParentRoute: () => DashboardRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/public/landing': typeof PublicLandingRouteRoute
  '/public/process': typeof PublicProcessRouteRoute
  '/public/signin': typeof PublicSigninRouteRoute
  '/public/signup': typeof PublicSignupRouteRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/projects/$projectId': typeof DashboardProjectsProjectIdRoute
  '/dashboard/projects/': typeof DashboardProjectsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/public/landing': typeof PublicLandingRouteRoute
  '/public/process': typeof PublicProcessRouteRoute
  '/public/signin': typeof PublicSigninRouteRoute
  '/public/signup': typeof PublicSignupRouteRoute
  '/dashboard': typeof DashboardIndexRoute
  '/dashboard/projects/$projectId': typeof DashboardProjectsProjectIdRoute
  '/dashboard/projects': typeof DashboardProjectsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/public/landing': typeof PublicLandingRouteRoute
  '/public/process': typeof PublicProcessRouteRoute
  '/public/signin': typeof PublicSigninRouteRoute
  '/public/signup': typeof PublicSignupRouteRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/projects/$projectId': typeof DashboardProjectsProjectIdRoute
  '/dashboard/projects/': typeof DashboardProjectsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/public/landing'
    | '/public/process'
    | '/public/signin'
    | '/public/signup'
    | '/dashboard/'
    | '/dashboard/projects/$projectId'
    | '/dashboard/projects/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/public/landing'
    | '/public/process'
    | '/public/signin'
    | '/public/signup'
    | '/dashboard'
    | '/dashboard/projects/$projectId'
    | '/dashboard/projects'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/public/landing'
    | '/public/process'
    | '/public/signin'
    | '/public/signup'
    | '/dashboard/'
    | '/dashboard/projects/$projectId'
    | '/dashboard/projects/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  PublicLandingRouteRoute: typeof PublicLandingRouteRoute
  PublicProcessRouteRoute: typeof PublicProcessRouteRoute
  PublicSigninRouteRoute: typeof PublicSigninRouteRoute
  PublicSignupRouteRoute: typeof PublicSignupRouteRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/public/signup': {
      id: '/public/signup'
      path: '/public/signup'
      fullPath: '/public/signup'
      preLoaderRoute: typeof PublicSignupRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/public/signin': {
      id: '/public/signin'
      path: '/public/signin'
      fullPath: '/public/signin'
      preLoaderRoute: typeof PublicSigninRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/public/process': {
      id: '/public/process'
      path: '/public/process'
      fullPath: '/public/process'
      preLoaderRoute: typeof PublicProcessRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/public/landing': {
      id: '/public/landing'
      path: '/public/landing'
      fullPath: '/public/landing'
      preLoaderRoute: typeof PublicLandingRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/projects/': {
      id: '/dashboard/projects/'
      path: '/projects'
      fullPath: '/dashboard/projects/'
      preLoaderRoute: typeof DashboardProjectsIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/projects/$projectId': {
      id: '/dashboard/projects/$projectId'
      path: '/projects/$projectId'
      fullPath: '/dashboard/projects/$projectId'
      preLoaderRoute: typeof DashboardProjectsProjectIdRouteImport
      parentRoute: typeof DashboardRoute
    }
  }
}

interface DashboardRouteChildren {
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardProjectsProjectIdRoute: typeof DashboardProjectsProjectIdRoute
  DashboardProjectsIndexRoute: typeof DashboardProjectsIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardProjectsProjectIdRoute: DashboardProjectsProjectIdRoute,
  DashboardProjectsIndexRoute: DashboardProjectsIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRouteWithChildren,
  PublicLandingRouteRoute: PublicLandingRouteRoute,
  PublicProcessRouteRoute: PublicProcessRouteRoute,
  PublicSigninRouteRoute: PublicSigninRouteRoute,
  PublicSignupRouteRoute: PublicSignupRouteRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
